baseURL = "https://almujahidinmosque.netlify.app/"
title = "Al-Mujahidin Mosque Kembangsri"
# post pagination
paginate = "6"
summaryLength = "10"
# disqusShortname = "almujahidinmosque" # get your shortname form here : https://disqus.com
disableLanguages = ["en"]
defaultContentLanguage = "id"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_footer = "images/logo_footer.svg"
# Meta data
description = "Masjid dengan program dakwah Kajian rutin, Subuh berkah, Jum'at berkah, Pasar Rakyat dan program lainnya. Terletak disisi jalan raya Ngoro, Kembangsri, Kec. Ngoro, Kabupaten Mojokerto, Jawa Timur."
author = "Al-Mujahidin Mosque"
# contact info
address = "Jl. Raden Wijaya No. 1, Ds. Kembangsri, Kec. Ngoro, Kabupaten Mojokerto, Jawa Timur 61385"
mobile = "+6281336762725"
email = "almujahidinmosque.or.id@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.svg" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-7.536192907739639"
map_longitude = "112.6237298118676"
map_marker = "images/marker.png" # marker size 37*55 px
# cookies
[params.cookies]
enable = true
expire_days = 2

 # themify icon : https://themify.me/themify-icons
[[params.social]]
title = "facebook"
icon = "ti-facebook"
link = "https://www.facebook.com/almujahidinmosque"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "https://twitter.com/almujahidinmosque"

[[params.social]]
title = "instagram"
icon = "ti-instagram"
link = "https://www.instagram.com/almujahidinmosque"

[[params.social]]
title = "github"
icon = "ti-github"
link = "https://github.com/almujahidinmosque"

# [[params.social]]
# title = "tiktok"
# icon = "ti-tiktok"
# link = "https://www.tiktok.com/@almujahidinmosque"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin"
# link = "#"

# Indonesia navigation

[Languages.id]
languageName = "ID"
languageCode = "id-id"
contentDir = "content/indonesia"
weight = 1
home = "Beranda"
# copyright
copyright = "Hakcipta &copy; 2023 Masjid Al-Mujahidin"

# Indonesia navigation

[[Languages.id.menu.main]]
weight = 2
name = "Berita"
hasChildren = true

  [[Languages.id.menu.main]]
  weight = 1
  parent = "Berita"
  name = "Artikel"
  url = "blog/"

  [[Languages.id.menu.main]]
  weight = 2
  parent = "Berita"
  name = "Acara"
  url = "event/"

  [[Languages.id.menu.main]]
  weight = 3
  parent = "Berita"
  name = "Publikasi"
  url = "publication/"

  [[Languages.id.menu.main]]
  weight = 4
  parent = "Berita"
  name = "Pemberitahuan"
  url = "notice/"

  [[Languages.id.menu.main]]
  weight = 5
  parent = "Berita"
  name = "Galeri"
  url = "gallery/"

  [[Languages.id.menu.main]]
  weight = 6
  parent = "Berita"
  name = "Dokumen"
  url = "document/"

[[Languages.id.menu.main]]
weight = 3
name = "Kajian"
hasChildren = true

  [[Languages.id.menu.main]]
  weight = 1
  parent = "Kajian"
  name = "Khotmil Al-Quran"
  url = "study/khotmil-quran/"

  [[Languages.id.menu.main]]
  weight = 2
  parent = "Kajian"
  name = "Pengajian Subuh Berkah"
  url = "study/subuh-blessing/"

  [[Languages.id.menu.main]]
  weight = 3
  parent = "Kajian"
  name = "Pengajian Tafsir Al-Quran"
  url = "study/quran-interpretation/"

  [[Languages.id.menu.main]]
  weight = 4
  parent = "Kajian"
  name = "Pengajian Tafsir Hadits"
  url = "study/hadith-interpretation/"

  [[Languages.id.menu.main]]
  weight = 5
  parent = "Kajian"
  name = "Tadarus Safari"
  url = "study/tadarus-safari/"

[[Languages.id.menu.main]]
weight = 4
name = "Agenda"
hasChildren = true

  [[Languages.id.menu.main]]
  weight = 1
  parent = "Agenda"
  name = "Idul Adha"
  url = "agenda/eid-al-adha/"

  [[Languages.id.menu.main]]
  weight = 2
  parent = "Agenda"
  name = "Idul Fitri"
  url = "agenda/eid-al-fitr/"

  [[Languages.id.menu.main]]
  weight = 3
  parent = "Agenda"
  name = "Ramadhan"
  url = "agenda/ramadhan/"

  [[Languages.id.menu.main]]
  weight = 4
  parent = "Agenda"
  name = "Pasar Rakyat"
  url = "agenda/public-market/"

  [[Languages.id.menu.main]]
  weight = 5
  parent = "Agenda"
  name = "Refleksi Akhir Tahun"
  url = "agenda/end-of-year-reflection/"

# reference: https://donasi.dompetdhuafa.org
[[Languages.id.menu.main]]
weight = 5
name = "Formulir"
hasChildren = true

  [[Languages.id.menu.main]]
  weight = 1
  parent = "Formulir"
  name = "Zakat/Infaq/Sedekah"
  url = "form/zis/"

  [[Languages.id.menu.main]]
  weight = 2
  parent = "Formulir"
  name = "Donasi Kemanusiaan"
  url = "form/human-donation/"

  [[Languages.id.menu.main]]
  weight = 3
  parent = "Formulir"
  name = "Waqaf"
  url = "form/waqaf/"

  [[Languages.id.menu.main]]
  weight = 4
  parent = "Formulir"
  name = "Tanya & Jawab"
  url = "form/question-answer/"

  [[Languages.id.menu.main]]
  weight = 5
  parent = "Formulir"
  name = "Pendataan"
  url = "form/data-collection/"

[[Languages.id.menu.main]]
weight = 6
name = "Profil"
hasChildren = true

  [[Languages.id.menu.main]]
  weight = 1
  parent = "Profil"
  name = "Sejarah"
  url = "profile/history/"

  [[Languages.id.menu.main]]
  weight = 2
  parent = "Profil"
  name = "Visi & Misi"
  url = "profile/vision-mission/"

  [[Languages.id.menu.main]]
  weight = 3
  parent = "Profil"
  name = "Dewan Takmir"
  url = "profile/takmir-council/"

  [[Languages.id.menu.main]]
  weight = 4
  parent = "Profil"
  name = "Remaja Masjid"
  url = "profile/mosque-youth/"

  [[Languages.id.menu.main]]
  weight = 5
  parent = "Profil"
  name = "Inventaris"
  url = "profile/inventory/"

  [[Languages.id.menu.main]]
  weight = 6
  parent = "Profil"
  name = "Lokasi"
  url = "profile/location/"

  [[Languages.id.menu.main]]
  weight = 7
  parent = "Profil"
  name = "Kontak"
  url = "profile/contact/"

# footer menu

[[Languages.id.menu.footer]]
name = "Pengajar"
url = "teacher/"

[[Languages.id.menu.footer]]
name = "Acara"
url = "event/"

[[Languages.id.menu.footer]]
name = "Pemberitahuan"
url = "notice/"

[[Languages.id.menu.footer]]
name = "Beasiswa"
url = "scholarship/"

[[Languages.id.menu.footer]]
name = "Penelitian"
url = "research/"

# English navigation

[Languages.en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2023 Al-Mujahidin Mosque"

# English navigation

[[Languages.en.menu.main]]
weight = 2
name = "News"
hasChildren = true

  [[Languages.en.menu.main]]
  weight = 1
  parent = "News"
  name = "Artikel"
  url = "blog/"

  [[Languages.en.menu.main]]
  weight = 2
  parent = "News"
  name = "Event"
  url = "event/"

  [[Languages.en.menu.main]]
  weight = 3
  parent = "News"
  name = "Publication"
  url = "publication/"

  [[Languages.en.menu.main]]
  weight = 4
  parent = "News"
  name = "Notice"
  url = "notice/"

  [[Languages.en.menu.main]]
  weight = 5
  parent = "News"
  name = "Gallery"
  url = "gallery/"

  [[Languages.en.menu.main]]
  weight = 6
  parent = "News"
  name = "Document"
  url = "document/"

[[Languages.en.menu.main]]
weight = 3
name = "Study"
hasChildren = true

  [[Languages.en.menu.main]]
  weight = 1
  parent = "Study"
  name = "Khotmil Al-Quran"
  url = "study/khotmil-quran/"

  [[Languages.en.menu.main]]
  weight = 2
  parent = "Study"
  name = "Subuh-study"
  url = "study/subuh-blessing/"

  [[Languages.en.menu.main]]
  weight = 3
  parent = "Study"
  name = "Al-Quran Interpretation Study"
  url = "study/quran-interpretation/"

  [[Languages.en.menu.main]]
  weight = 4
  parent = "Study"
  name = "Hadith Interpretation Study"
  url = "study/hadith-interpretation/"

  [[Languages.en.menu.main]]
  weight = 5
  parent = "Study"
  name = "Tadarus Safari"
  url = "study/tadarus-safari/"

[[Languages.en.menu.main]]
weight = 4
name = "Agenda"
hasChildren = true

  [[Languages.en.menu.main]]
  weight = 1
  parent = "Agenda"
  name = "Eid al-Adha"
  url = "agenda/eid-al-adha/"

  [[Languages.en.menu.main]]
  weight = 2
  parent = "Agenda"
  name = "Eid al-Fitr"
  url = "agenda/eid-al-fitr/"

  [[Languages.en.menu.main]]
  weight = 3
  parent = "Agenda"
  name = "Ramadhan"
  url = "agenda/ramadhan/"

  [[Languages.en.menu.main]]
  weight = 4
  parent = "Agenda"
  name = "Public Market"
  url = "agenda/public-market/"

  [[Languages.en.menu.main]]
  weight = 5
  parent = "Agenda"
  name = "End of Year Reflection"
  url = "agenda/end-of-year-reflection/"

# reference: https://donasi.dompetdhuafa.org
[[Languages.en.menu.main]]
weight = 5
name = "Form"
hasChildren = true

  [[Languages.en.menu.main]]
  weight = 1
  parent = "Form"
  name = "Zakat/Infaq/Sedekah"
  url = "form/zis/"

  [[Languages.en.menu.main]]
  weight = 2
  parent = "Form"
  name = "Human Donation"
  url = "form/human-donation/"

  [[Languages.en.menu.main]]
  weight = 3
  parent = "Form"
  name = "Waqaf"
  url = "form/waqaf/"

  [[Languages.en.menu.main]]
  weight = 4
  parent = "Form"
  name = "Question & Answer"
  url = "form/question-answer/"

  [[Languages.en.menu.main]]
  weight = 5
  parent = "Form"
  name = "Data Collection"
  url = "form/data-collection/"

[[Languages.en.menu.main]]
weight = 6
name = "Profile"
hasChildren = true

  [[Languages.en.menu.main]]
  weight = 1
  parent = "Profile"
  name = "History"
  url = "profile/history/"

  [[Languages.en.menu.main]]
  weight = 2
  parent = "Profile"
  name = "Vision & Mission"
  url = "profile/vision-mission/"

  [[Languages.en.menu.main]]
  weight = 3
  parent = "Profile"
  name = "Takmir Council"
  url = "profile/takmir-council/"

  [[Languages.en.menu.main]]
  weight = 4
  parent = "Profile"
  name = "Mosque Youth"
  url = "profile/mosque-youth/"

  [[Languages.en.menu.main]]
  weight = 5
  parent = "Profile"
  name = "Inventory"
  url = "profile/inventory/"

  [[Languages.en.menu.main]]
  weight = 6
  parent = "Profile"
  name = "Location"
  url = "profile/location/"

  [[Languages.en.menu.main]]
  weight = 7
  parent = "Profile"
  name = "Contact"
  url = "profile/contact/"

# footer menu

[[Languages.en.menu.footer]]
name = "Teacher"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "Notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "Event"
url = "event/"

[[Languages.en.menu.footer]]
name = "Scholarship"
url = "scholarship/"

[[Languages.en.menu.footer]]
name = "Research"
url = "research/"
