######################## default configuration ####################
baseURL = "https://almujahidinmosque.netlify.app/"
title = "Al-Mujahidin Mosque Kembangsri"
# post pagination
paginate = "6"
summaryLength = "10"
disqusShortname = "almujahidinmosque" # get your shortname form here : https://disqus.com
disableLanguages = ["en"]
defaultContentLanguage = "id"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
# Meta data
description = "Masjid yang memberikan program dakwah seperti Kajian tematik, Subuh berkah, Jum'at berkah, halal bi halal dan program lainnya. Masjid ini terletak disisi jalan raya Ngoro, Kembangsri, Kec. Ngoro, Kabupaten Mojokerto, Jawa Timur."
author = "Al-Mujahidin"
# contact info
address = "Jl. Ngoro, Kembangsri, Kec. Ngoro, Kabupaten Mojokerto, Jawa Timur 61385"
mobile = "+6281336762725"
email = "almujahidinmosque.or.id@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.svg" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-7.536192907739639"
map_longitude = "112.6237298118676"
map_marker = "images/marker.png" # marker size 37*55 px
# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/almujahidinmosque"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/almujahidinmosque"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/almujahidinmosque"

[[params.social]]
title = "tiktok"
icon = "ti-tiktok" # themify icon : https://themify.me/themify-icons
link = "https://www.tiktok.com/@almujahidinmosque"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/almujahidinmosque"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
# link = "#"

################################### Indonesia language #####################################
[Languages.id]
languageName = "ID"
languageCode = "id-id"
contentDir = "content/indonesia"
weight = 1
home = "Beranda"
# copyright
copyright = "Hakcipta &copy; 2023 Masjid Al-Mujahidin"

################### Indonesia navigation ####################

[[Languages.id.menu.main]]
name = "Blog"
url = "blog/"
weight = 1

[[Languages.id.menu.main]]
weight = 2
name = "Halaman"
hasChildren = true

  [[Languages.id.menu.main]]
  parent = "Halaman"
  name = "Pengajar"
  url = "teacher/"

  [[Languages.id.menu.main]]
  parent = "Halaman"
  name = "Pemberitahuan"
  url = "notice/"

  [[Languages.id.menu.main]]
  parent = "Halaman"
  name = "Acara"
  url = "event/"

  [[Languages.id.menu.main]]
  parent = "Halaman"
  name = "Beasiswa"
  url = "scholarship/"

  [[Languages.id.menu.main]]
  parent = "Halaman"
  name = "Penelitian"
  url = "research/"

[[Languages.id.menu.main]]
name = "Kursus"
url = "course/"
weight = 3

# main menu
[[Languages.id.menu.main]]
name = "Profil"
url = "about/"
weight = 4

[[Languages.id.menu.main]]
name = "Kontak"
url = "contact/"
weight = 5

# footer menu

[[Languages.id.menu.footer]]
name = "Pengajar"
url = "teacher/"

[[Languages.id.menu.footer]]
name = "Pemberitahuan"
url = "notice/"

[[Languages.id.menu.footer]]
name = "Acara"
url = "event/"

[[Languages.id.menu.footer]]
name = "Beasiswa"
url = "scholarship/"

[[Languages.id.menu.footer]]
name = "Penelitian"
url = "research/"

################################### English language #####################################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2023 Al-Mujahidin Mosque"

################### English navigation ####################

[[Languages.en.menu.main]]
name = "blog"
url = "blog/"
weight = 1

[[Languages.en.menu.main]]
weight = 2
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"

[[Languages.en.menu.main]]
name = "course"
url = "course/"
weight = 3

# main menu
[[Languages.en.menu.main]]
name = "Profile"
url = "about/"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu

[[Languages.en.menu.footer]]
name = "Teacher"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "Notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "Event"
url = "event/"

[[Languages.en.menu.footer]]
name = "Scholarship"
url = "scholarship/"

[[Languages.en.menu.footer]]
name = "Research"
url = "research/"
